### ISSUE TITLE
Crash when viewing the JEI recipe category.

### ISSUE THREAD

**Issue by Darkhax** [MtcLeo05/Soulmancy#32]
Hey, I was testing out a few mods while building the SpookyJam submissions modpack and noticed a crash when attempting to view the soul transformation category in JEI. 

Minecraft: 1.21.1
NeoForge: 21.1.74
Soulmancy: 1.0.0

[soulmancy_crash_log.txt](https://github.com/user-attachments/files/17732101/soulmancy_crash_log.txt)

**Comment by MtcLuna05** [comment]
I probably built on an older JEI version, I'll check it asap with latest

**Comment by MtcLuna05** [comment]
After testing with neoforge 21.1.74 and latest jei I could unfortunately not reproduce the issue. Is it possible some other mod is causing incompatibilities?
Also this mod requires terrablender and accessories to function properly, and in the list of mods provided they are not present.
I know they should not be related, since terrablender is for worldgen and accessories is for the items, but the mod does require them to run

**Comment by Darkhax** [comment]
Hey, both terrablender and accessories are shown in the log file. After looking into the issue more, it looks like CurseForge is serving outdated versions of JEI because the new ones are marked as beta. It might be a good idea to update the minimum version range in your mod to catch this issue early.

**Comment by MtcLuna05** [comment]
Will push a fix with the new version range, is there anything else that's broken that you noticed?

**Comment by Darkhax** [comment]
Thanks, no I haven't noticed anything else.
